language: 'python'
python:
  - '3.6'
script:
  - 'true'
deploy:
  provider: 'pypi'
  user: 'hardwario'
  password:
    secure: 'P6Aq6s6HP8FzF6aZX7l8H1hr7k7gQVinq5JzS8pSiq29SBwd3e6RFLyUbwLNjPY0oRQkKGo81jbUGMYbiZ+Nkw/I93ejnmB+ujitQsHB3hGfPprOFkrn2yIjq9a3nihTOWVTJyWAy6ZoSNswNi1RY051d4aBSJRIuOnOQdrnlHtG22fm0bQCKkK64V344Y6Oy5rPYwDa8YtAqqN0WDosCxTbT9TllyD3Z3EbRH/4cJgZ/RvbSvG5WaeSQ8gEO3Ts/UoHt6NHVsEiZnQbyganhjKeH1cj/D2hfm6gxddB3sNxqsT9JJL+CmNd4itu5YqBCXE0t0JvnKw5kje32AGIsThAz1tUkN9iWf6Uq2G/FYOeMfaPZnJxAK9LmJUlQLYCOmUq+Z9ZKvfB7tR3Uv3GRyWp7ivzYfwy3FNqIUtboRsZlyclnEtSIQcr0A4BqNcX99zs/qR9ZapmVGvloB8/rm9vl1NonmAz3RF5O5lYmdUCtMJPkcRxMEr2JhItvS7HGH12OnMk+joFYOon4hcXVn1LWFEcLDrmhv5vpV0LmxwrZpt189FV4SVKBIl4QfSK18hsWAaMFgOVd5/znu867yCVG6jTaHlfficlPJlEso0h0kaSDkRvosA89lmfr25dxiWOoDiXJQPCmifC0rPysB3zs4F+HigcKzJcjts+MtE='
  distributions: 'sdist bdist_wheel'
  on:
    tags: true
